# Generated by Django 5.2.14 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready for Collection/Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
